### PR TITLE
Total climate pollution chart & projection to 0 by 2050

### LINKED ISSUE #17: Add Homepage Total US Pollution Chart with Projection to 0 by 2050
Using `Recharts` create a new Component chart that shows current US emissions and what we need to do to get to 0 by 2050:

Example spreadsheet and chart: https://docs.google.com/spreadsheets/d/1QIWu0BSWCW2AgrJilhcsPA20jTdDjxqNJGoMx9c8-Iw/edit#gid=0

Screen Shot 2022-03-08 at 4 46 55 PM

Steps

1. Create a function to generate the projected emissions from a given year until 2050 to get to zero
2. Create a new component based on `SimpleAreaChart` with 2 series (actual + projection) https://recharts.org/en-US/examples/SimpleAreaChart 
3. Add the component to the home page and pass in US total emissions
4. Add the component to the state detail page and pass in that state's emissions

### PR DESCRIPTION
**Pull request by hkier**
## Overview
This PR adds the area chart to both the index and state detail pages.

Closes #17 

### Demo
[What does it take to decarbonize your state .pdf](https://github.com/chihacknight/state-by-state-decarbonization/files/8366505/What.does.it.take.to.decarbonize.your.state.pdf)

## Testing Instructions

This PR can be tested by loading the app and visually looking at the area chart on both the index and state pages.  Various state pages should be check to verify proper functioning.

### CODE REVIEW

**Comment by nofurtherinformation** [comment]
Awesome! A couple suggestions:
- This component should be responsive, so that it will also look great on smaller screens -- check out how the stacked bar chart uses the `ResponsiveContainer` component from recharts [here](https://github.com/chihacknight/state-by-state-decarbonization/blob/5b0a00d87486d46ec710b72bace70e05fc8eec04/src/components/stackedbar.js#L79)
- For the `emissions_data` property that this component takes, if you wrap that in curly braces `{}` in the function, you can use it directly instead of using `Object.values(emissions_data)[0]` (see [here](https://github.com/chihacknight/state-by-state-decarbonization/blob/5b0a00d87486d46ec710b72bace70e05fc8eec04/src/components/stackedbar.js#L75) for reference). For more on what's going on with this syntax, object destructuring, check out [this article](https://dmitripavlutin.com/javascript-object-destructuring/)
- On the design-side, I'd considering ditching the legend for in-chart labels, something like this:
Screen Shot 2022-03-28 at 7 20 28 PM
A rough approach to this could look like:

```javascript
   // other component stuff
    <ReferenceLine x="2018" stroke="none" label={{value:"Emissions", angle:90, fill:"#b65c00"}} />
    <ReferenceLine x="2024" stroke="none" label={{value:"Projections", angle:90, fill:"#36a654"}} />
    // rest of component stuff
```

**Comment by derekeder** [comment]
@hkier looks like this is failing on build because it is referencing `guam` which @vkoves removed in https://github.com/chihacknight/state-by-state-decarbonization/commit/ccb1cd6f9c8fffd96de9a366a7e97909ba00873f. If you pull down the latest changes from `main` to your branch, it should build

**Comment by hkier** [comment]
When I attempted to update my branch from main, I was informed I was up to date.  I did attempt another commit and it is showing 1 file conflict which is just deleting a blank line.  Not sure what else might be causing the problem/conflicts.

**Comment by derekeder** [comment]
@hkier ok - if you are coming to hack night tonight, we can spend some time and sort it out. looks like we also have some merge conflicts with the recently merged in PR #40 that we will also have to resolve

**Comment by hkier** [comment]
Derek,  sorry but I have a meeting conflict this evening and was not planning to attend.  Even if I were to drop in for a couple of minutes (from my other meetings) I would not have my coding computer available for screen sharing and diagnostic work.  

I see this:
`Add more commits by pushing to the [Total-climate-pollution-chart-&-projection-to-0-by-2050](https://github.com/hkier/state-by-state-decarbonization/tree/Total-climate-pollution-chart-%26-projection-to-0-by-2050) branch on [hkier/state-by-state-decarbonization](https://github.com/hkier/state-by-state-decarbonization).`

I wonder if this might be the problem and if so, I need to remember how to push to a specific repo/branch.

**Review by derekeder — APPROVED** [review]

**Pull request merged**
