### PR TITLE
cleanup the single bar component

### LINKED ISSUE #17: Add Homepage Total US Pollution Chart with Projection to 0 by 2050
Using `Recharts` create a new Component chart that shows current US emissions and what we need to do to get to 0 by 2050:

Example spreadsheet and chart: https://docs.google.com/spreadsheets/d/1QIWu0BSWCW2AgrJilhcsPA20jTdDjxqNJGoMx9c8-Iw/edit#gid=0

Screen Shot 2022-03-08 at 4 46 55 PM

Steps

1. Create a function to generate the projected emissions from a given year until 2050 to get to zero
2. Create a new component based on `SimpleAreaChart` with 2 series (actual + projection) https://recharts.org/en-US/examples/SimpleAreaChart 
3. Add the component to the home page and pass in US total emissions
4. Add the component to the state detail page and pass in that state's emissions

### LINKED ISSUE #18: Create stacked bar chart for one year
Create a new `Recharts` component for a single stacked bar so we can start generating charts like this:

Screen Shot 2022-03-08 at 4 55 37 PM

We can then reuse this component on the Home page:

Screen Shot 2022-03-08 at 4 56 24 PM

and throughout the state detail page:

Screen Shot 2022-03-08 at 4 56 48 PM
Screen Shot 2022-03-08 at 4 56 57 PM

We can use this as a starting example: https://recharts.org/en-US/examples/StackedBarChart

### PR DESCRIPTION
**Pull request by derekeder**
## Overview

Small PR to clean up the code from #36 and place it in the proper place on the home page

Closes #18 

### Demo

Screen Shot 2022-03-22 at 10 09 36 PM

## Testing Instructions

* confirm the single stacked bar chart renders as expected on the home page

### CODE REVIEW

**Comment by nofurtherinformation** [comment]
Hey @derekeder, was just taking a look at this out of curiosity, one more peculiarity of the `content` property on `LabelList` is that it exposes the additive y axis value for each stacked bar, not the source data value value (so, buildings appears as to represent ~57%, since that is its total accumulated amount in the stack, but not individual percent). 

`valueAccessor` exposes the actual data value though, so something like the below works -- what do you think? Happy to push on this PR if ok!

```javascript
// helpers

const getPct = (value, total) => { return Math.round((value/total)*100) }
const getLabel = (
  entry, 
  total, 
  field, 
  label
) => { 
  return `${label}: ${getPct(entry[field], total)}%` 
}

function SingleBarChart ({emissions_data}) {
  // sum all emissions fields except year
  const totalEmissions = Object.entries(emissions_data[0])
    .filter((key) => key !== 'year')
    .reduce((acc, curr) => acc + curr[1], 0);
  // ... some lines later
  <Bar dataKey="dumps_farms_industrial_other" stackId="a" fill="#98886c">
          <LabelList valueAccessor={entry => getLabel(
            entry, 
            totalEmissions, 
            'dumps_farms_industrial_other', 
            'Dumps, Farms, Industrial & Other'
            )} 
            position="insideTopLeft" /> 
  </Bar>
}
```

Looks like:
Screen Shot 2022-03-23 at 9 11 25 AM

**Comment by derekeder** [comment]
@nofurtherinformation nice! one question for the bar in your screenshot, why do the totals add up to less than 100%? (20 + 7 + 23  + 28 = 78%)

**Comment by nofurtherinformation** [comment]
🤦‍♀️ My bad on that one, the filter statement wasn’t destructuring the keys properly, so wasn’t removing the year data. Will push a commit here once I’m back home

**Comment by vkoves** [comment]
@derekeder - this look solid but I don't think it actually closes #17, since that also includes a drawdown graph showing emissions going down to 0. I think this does close Issue #29.

Also could we move the axis closer to the actual data? It's really hard to read in my mind since it's so far away. However, if the specific Gigatonne values don't matter (which I am open to, since it's basically for showing percentages), we could just drop the axis and the label.

**Comment by derekeder** [comment]
@nofurtherinformation nice - this looks correct now. Thanks for the assist

@vkoves I agree the YAxis is a bit far away. It doesn't give us much value so I removed it. Also updated the issue description so it closes #18, which was mistakenly closed from the previous PR #36.

This is ready for another look

**Review by vkoves — APPROVED** [review]
Awesome work! There's a few unused variables and imports GitHub is pointing out, but I don't think that's a blocker - I'd rather get this merged so I can integrate it on the state details page and start figuring out how to highlight individual sections as green.

**Comment by derekeder** [comment]
@vkoves cool. I removed those references. Once it builds I'll bring this in.

**Pull request merged**
