### PR TITLE
Make State Details Graph Stick On Desktop (& Fix Homepage Electrification Lines)

### LINKED ISSUE #46: Make State Details Page Graph Sticky
Make the graph order match the section order and make the graph sticky, using a scroll observer to update the graph based on where you are on the page.

### PR DESCRIPTION
**Pull request by vkoves**
## Overview

Move the large desktop layout to a consistent two column layout where a single stacked bar chart follows you along the page, animating between the different states we have setup. Additionally, the text fades in and out to accompany the graph, like so:

https://user-images.githubusercontent.com/3187531/163510318-d28a17e5-af6e-4f1f-aff2-29d52064d380.mp4

Closes #46

### Demo

See Overview.

### Notes

I used [react-scrollspy](https://www.npmjs.com/package/react-scrollspy) for this but it was recently deprecated. However since it is so light-weight I think that's okay.

## Testing Instructions

- Confirm the graph updates properly as you scroll on desktop (> 1200px wide)
- Confirm you see a proper alternating two column layout on tablet (768 - 1200px wide)
- Confirm you see a fully one column layout on mobile (< 768px wide)

### CODE REVIEW

**Comment by vkoves** [comment]
@derekeder - I've updated the active indication per our Slack discussion to use a border rather than a fade out/in, let me know what you think! I can also add a background or tweak it any other way

https://user-images.githubusercontent.com/3187531/163692678-72f920b7-5e60-48fa-9d07-1657422aee01.mp4

**Review by derekeder — APPROVED** [review]
@vkoves this is great! nice and smooth and the sections transition/animate beautifully!

I have a few notes on how the colors should change and what should be highlighted:

* above the bar on the left, we should put a title like "Climate pollution in XX by source"
* the power bar on the left is serving as a kind of navigation element for the page. Instead of highlighting the vertical bar for the right content section, we should highlight the part of the bar chart that we're on instead. I know we're using the green / orange already, but I think moving the vertical bar over to the bar chart would help
* as we scroll down, we are waving our magic wand and eliminating all of the emissions from each category. To help reinforce this, I think the green areas should stay green once we change them. That will also indicate scroll progress on the page.

What do you think? I think if we can resolve these (hopefully small) changes, we can bring this in.

**Comment by jpvelez** [comment]
- I think it's more intuitive to have the emissions decline and disappear after we scale up the solutions in each section, as suggested here: https://github.com/chihacknight/state-by-state-decarbonization/issues/50
This approach matches the line chart at the top of the page - how we make the emissions decline until they are gone.

**Comment by jpvelez** [comment]
Also, I think adding some emojis to the bar chart will help make things more visual and intuitive:

🏠 Buildings: X%
🚗 Transport: X%
🏭 Power: X%

**Comment by vkoves** [comment]
@derekeder - I've updated the graph to stay green in the sticky full desktop mode, and added emoji as Juan-Pablo suggested. With recharts it is pretty challenging to add a line to the right of a graph section, but it's easy for me to change the fill color if you have any suggestions there.

Also making the emissions fully remove can be tackled separately, as this PR is already pretty large.

Here's a demo of the new changes:

https://user-images.githubusercontent.com/3187531/163893842-93f46302-2d53-414f-b377-d71a33d204f1.mp4

I also noticed the state icons were broken with states with spaces in the name (from moving to hyphens in underscore, likely with the GraphQL refactor)

**Comment by vkoves** [comment]
Another minor update: I've made it so that numerical values show in a more human readable way, as "XX million" or "YY,000" rather than precise numbers. It felt weird that our site was saying _to the individual house_ how many boilers we'd need to replace per year. I'm also open to changing this to "YY thousand" but for me "YY,000" felt clearer :man_shrugging: 

| Before | After |
| --- | --- |
| Screenshot from 2022-04-18 19-33-07 | Screenshot from 2022-04-18 19-33-43 |

**Review by derekeder — DISMISSED** [review]
this looks great! I agree we can bring this in and address the other feedback in a separate PR. 

Also +1 to making the large numbers more friendly to read.

**Review by derekeder — APPROVED** [review]
@vkoves sounds good for now. I imagine we'll take more passes through the copy after the primary implementation is done.

**Pull request merged**
