### PR TITLE
Data scripts to json

### PR DESCRIPTION
**Pull request by swatland610**
## Summary of Changes
* Edits to the `get_emissions.py` file that just: 
    * Reads in the `raw` data
    * Feeds `raw` into the helper functions
    * prints the output of the helper as a json object

* Created the `get_generation.py` file that does the exact same thing as described above. 

* Edits to `utils.py` that: 
    *  only keeps the columns we need for respective data
    * sets the multi index of `(state, year)` 
    * removes unnecessary comments in code

## Expected Output
The json object output for final should look like this: 
```
{'metric_label':
     {"(`state', year)":actual_value,
      for all 50 states for all years....},
{'new_metric_label': etc...}
```

Ready for your review whenever @derekeder

### CODE REVIEW

**Comment by derekeder** [comment]
looks like it failed to build because it thinks the `data/decarbonize_us_analysis` is a submodule. I removed the folder since we pulled out what we need from it.

**Comment by derekeder** [comment]
I removed old references to the `allOccupationsJson` that we're no longer using to get the builds to pass, but it looks like we'll need to get the `emissions.json` data in shape before making any more progress on it.

@swatland610 once that data is prepped, let me know and I'll work to get the site building with the new data

**Comment by swatland610** [comment]
@derekeder Alright, I've added a helper in the [utils.py](https://github.com/chihacknight/state-by-state-decarbonization/blob/data_scripts_to_json/data/scripts/utils.py) file. 

I've also adjusted both the `get_data` files to remove some redundancies. Let me know if the output is not working for you! I got it working this morning.

**Comment by derekeder** [comment]
making progress! 
Screen Shot 2022-02-10 at 10 47 53 PM

**Comment by derekeder** [comment]
charts! 
Screen Shot 2022-02-10 at 11 47 26 PM

**Comment by derekeder** [comment]
yay - its building now. I'm going to merge this in now so we have something to share with the group. I'll open an issue with a few requests for the data.

closes #2 
closes #4 
closes #3

**Pull request merged**
